//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Blit.rc
//
#define IDR_IMAGE2                      102
#define IDR_IMAGE3                      103
#define IDR_IMAGE4                      104
#define IDR_IMAGE5                      105
#define IDR_IMAGE6                      115
#define IDB_TINYFONT                    116
#define IDB_BIGFONT                     117
#define IDB_OPTIONS                     122
#define IDB_HIGHSCORES                  135
#define IDB_HIGHSCORESDOWN              139
#define IDB_NEWGAMEDOWN                 140
#define IDB_OPTIONSDOWN                 141
#define IDB_MAINMENUDOWN                148
#define IDB_NEWGAME2                    149
#define IDI_ICON1                       157
#define IDR_WAVE1                       165
#define IDB_congrats                    167
#define IDR_WAVE2                       169
#define IDB_NUMBERS                     206
#define IDB_EXITDOWN2                   207
#define IDB_NEWHIGHSCORE                220
#define IDB_A_HIGHSCORES                221
#define IDB_A_NEWHIGHSCORE              221
#define IDB_SIP                         223
#define IDB_FONT8                       224
#define IDB_FONT16                      225
#define IDB_SIPDOWN                     226
#define IDB_JOGGLEBACKGROUND            227
#define IDB_JOGGLESQUARE                228
#define IDB_JOGGLEZ                     229
#define IDB_JOGGLEA                     230
#define IDB_JOGGLEB                     231
#define IDB_JOGGLEC                     232
#define IDB_JOGGLED                     233
#define IDB_JOGGLEE                     234
#define IDB_JOGGLEF                     235
#define IDB_JOGGLEG                     236
#define IDB_JOGGLEH                     237
#define IDB_JOGGLEHIGHLIGHTEDA          238
#define IDB_JOGGLEHIGHLIGHTEDB          239
#define IDB_JOGGLEHIGHLIGHTEDC          240
#define IDB_JOGGLEHIGHLIGHTEDD          241
#define IDB_JOGGLEHIGHLIGHTEDE          242
#define IDB_JOGGLEHIGHLIGHTEDF          243
#define IDB_JOGGLEHIGHLIGHTEDG          244
#define IDB_JOGGLEHIGHLIGHTEDH          245
#define IDB_JOGGLEHIGHLIGHTEDI          246
#define IDB_JOGGLEHIGHLIGHTEDJ          247
#define IDB_JOGGLEHIGHLIGHTEDK          248
#define IDB_JOGGLEHIGHLIGHTEDL          249
#define IDB_JOGGLEHIGHLIGHTEDM          250
#define IDB_JOGGLEHIGHLIGHTEDN          251
#define IDB_JOGGLEHIGHLIGHTEDO          252
#define IDB_JOGGLEHIGHLIGHTEDP          253
#define IDB_JOGGLEHIGHLIGHTEDQ          254
#define IDB_JOGGLEHIGHLIGHTEDQU         255
#define IDB_JOGGLEHIGHLIGHTEDR          256
#define IDB_JOGGLEHIGHLIGHTEDS          257
#define IDB_JOGGLEHIGHLIGHTEDT          258
#define IDB_JOGGLEHIGHLIGHTEDU          259
#define IDB_JOGGLEHIGHLIGHTEDV          260
#define IDB_JOGGLEHIGHLIGHTEDW          261
#define IDB_JOGGLEHIGHLIGHTEDX          262
#define IDB_JOGGLEHIGHLIGHTEDY          263
#define IDB_JOGGLEHIGHLIGHTEDZ          264
#define IDB_JOGGLEI                     265
#define IDB_JOGGLEJ                     266
#define IDB_JOGGLEK                     267
#define IDB_JOGGLEL                     268
#define IDB_JOGGLEM                     269
#define IDB_JOGGLEN                     270
#define IDB_JOGGLEO                     271
#define IDB_JOGGLEP                     272
#define IDB_JOGGLEQ                     273
#define IDB_JOGGLEQU                    274
#define IDB_JOGGLER                     275
#define IDB_JOGGLES                     276
#define IDB_JOGGLET                     277
#define IDB_JOGGLEU                     278
#define IDB_JOGGLEV                     279
#define IDB_JOGGLEW                     280
#define IDB_JOGGLEX                     281
#define IDB_JOGGLEY                     282
#define IDB_JOGGLEBACKGROUND2           283
#define IDB_JOGGLECLEAR                 284
#define IDB_JOGGLEENTER                 285
#define IDB_JOGGLEMENU                  286
#define IDB_JOGGLEMENUUP                287
#define IDB_JOGGLECLEARUP               288
#define IDB_JOGGLEENTERUP               289
#define IDB_JOGGLEROUND1                290
#define IDB_JOGGLEROUND2                291
#define IDB_JOGGLEROUND4                292
#define IDB_CENTAURFONT                 293
#define IDB_BOOKMANFONT                 294
#define IDB_DOUBLEWORD                  295
#define IDB_TRIPLEWORD                  296
#define IDB_LETTERPICKED                297
#define IDB_RGBARROWS                   298
#define IDB_ALPHAARROWS                 299
#define IDB_AROUND1                     300
#define IDB_AROUND2                     301
#define IDB_AROUND3                     302
#define IDB_RGBROUND1                   303
#define IDB_RGBROUND2                   304
#define IDB_RGBROUND3                   305
#define IDB_BOTTOMARROW2                306
#define IDB_TOPARROW                    307
#define IDB_SCROLLBAR                   308
#define IDB_JOGGLETITLESCREEN           309
#define IDB_EXITDOWN3                   310
#define IDB_EXIT                        311
#define IDB_NEWGAME                     312
#define IDB_HIGHSCORESBUTTON            314
#define IDB_HIGHSCORESBUTTONDOWN        315
#define IDB_RULESDOWN                   316
#define IDB_RULES                       317
#define IDB_NEWGAME3                    318
#define IDB_RESULTS                     319
#define IDB_ZSMALL                      320
#define IDB_YSMALL                      321
#define IDB_XSMALL                      322
#define IDB_WSMALL                      323
#define IDB_VSMALL                      324
#define IDB_USMALL                      325
#define IDB_TSMALL                      326
#define IDB_SSMALL                      327
#define IDB_RSMALL                      328
#define IDB_QUSMALL                     329
#define IDB_PSMALL                      330
#define IDB_OSMALL                      331
#define IDB_NSMALL                      332
#define IDB_MSMALL                      333
#define IDB_LSMALL                      334
#define IDB_KSMALL                      335
#define IDB_JSMALL                      336
#define IDB_ISMALL                      337
#define IDB_HSMALL                      338
#define IDB_GSMALL                      339
#define IDB_FSMALL                      340
#define IDB_ESMALL                      341
#define IDB_DSMALL                      342
#define IDB_CSMALL                      343
#define IDB_BSMALL                      344
#define IDB_ASMALL                      345
#define IDB_RGBROUNDOVER                346
#define IDB_AROUNDOVER                  347
#define IDB_RESULTS3                    348
#define IDB_RESULTS2                    349
#define IDB_RESULTS1                    350
#define IDB_RESULTS4                    351
#define IDB_RGBNEXTROUNDDOWN            352
#define IDB_ABACKTOMAINMENU             353
#define IDB_ABACKTOMAINMENUDOWN         354
#define IDB_ANEXTROUND                  355
#define IDB_ANEXTROUNDDOWN              356
#define IDB_RGBBACKTOMAINMENU           357
#define IDB_RGBBACKTOMAINMENUDOWN       358
#define IDB_RGBNEXTROUND                359
#define IDB_FINALRESULTS                360
#define IDB_RGBTOFINALRESULTSDOWN       361
#define IDB_ATOFINALRESULTS             362
#define IDB_ATOFINALRESULTSDOWN         363
#define IDB_RGBTOFINALRESULTS           364
#define IDB_RULESBACKGROUND             365
#define IDB_NEXT                        366
#define IDB_NEXTDOWN                    367
#define IDB_RULESBACKGROUND2            368
#define IDB_RULESBACKGROUND4            369
#define IDB_RULESBACKGROUND3            370
#define IDB_RGBSMALLMENU                371
#define IDB_ASMALLMENU                  372
#define IDB_SMALLMENU                   373
#define IDB_SMALLMENU2                  374
#define IDB_ATIME1                      375
#define IDB_ATIME2                      376
#define IDB_ATIME3                      377
#define IDB_RGBTIME1                    378
#define IDB_RGBTIME2                    379
#define IDB_RGBTIME3                    380
#define IDB_LOADING                     381
#define IDR_CLICK                       382
#define IDR_MENUSLIDE                   383
#define IDR_ROUNDOVER                   384
#define IDR_CORRECT                     385
#define IDR_WAVE3                       386
#define IDR_INTERFACE                   386

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        387
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
